# Aula 02 - Numpy 
Biblioteca para processamento de arrays de uso geral, que fornece um conjunto de funcoes e metodos uteis para trabalhar arrays de multiplas dimensoes. Travis Oliphant foi o criador do numpy

In [1]:
# Matrizes em Numpy
import numpy as np

array = np.array([[1,2,3], [4,2,2]])

In [2]:
pip install pandas

Defaulting to user installation because normal site-packages is not writeable

[notice] A new release of pip is available: 24.2 -> 24.3.1
[notice] To update, run: python3 -m pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.


In [3]:
type(array)

numpy.ndarray

In [4]:
print(array.ndim)

2


In [5]:
print(array.size)

6


In [6]:
print(array.dtype)

int64


In [7]:
print(array.shape)

(2, 3)


In [8]:
array2 = np.array([[1,2,3], [4,2,2]], dtype=float)

In [9]:
print(array2)

[[1. 2. 3.]
 [4. 2. 2.]]


In [10]:
print(array2.dtype)

float64


In [11]:
array3 = np.array((1,2,3))

In [12]:
array3

array([1, 2, 3])

In [13]:
# cria uma matriz 4,6 de 1
array4 = np.ones((4,6))

In [14]:
array4

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [15]:
array5 = np.zeros((4,6))

In [16]:
array5

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [17]:
array6 = np.full((3,3), 6, dtype=complex)

In [18]:
array6

array([[6.+0.j, 6.+0.j, 6.+0.j],
       [6.+0.j, 6.+0.j, 6.+0.j],
       [6.+0.j, 6.+0.j, 6.+0.j]])

In [19]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [20]:
np.arange(0,30,3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [21]:
np.linspace(0,10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [22]:
array7 = np.array([[1,2,3,4], [5, 4, 3, 2], [9,8,7,6]])

In [23]:
print(array7)

[[1 2 3 4]
 [5 4 3 2]
 [9 8 7 6]]


In [24]:
array8 = array7.reshape(2,2,3)

In [25]:
print(array8)

[[[1 2 3]
  [4 5 4]]

 [[3 2 9]
  [8 7 6]]]


In [26]:
array9 = np.array([[1,2,3,4], [5, 4, 3, 2]])

In [27]:
array_flat = array9.flatten()

In [28]:
print(array_flat)

[1 2 3 4 5 4 3 2]


In [29]:
array10 = np.array([[1,2,-3,4,5], [-5, 4, 3, 2,9], [4, 8,-3,4,0], [1,2,3,-4,9]])

In [30]:
print(array10)

[[ 1  2 -3  4  5]
 [-5  4  3  2  9]
 [ 4  8 -3  4  0]
 [ 1  2  3 -4  9]]


In [31]:
temporario = array10[:2, ::2]

In [32]:
print(temporario)

[[ 1 -3  5]
 [-5  3  9]]


In [33]:
condicional = array10 > 0

In [34]:
temporario2 = array10[condicional]

In [35]:
print(temporario2)

[1 2 4 5 4 3 2 9 4 8 4 1 2 3 9]


In [36]:
print(array10**2)

[[ 1  4  9 16 25]
 [25 16  9  4 81]
 [16 64  9 16  0]
 [ 1  4  9 16 81]]


In [37]:
print(array10*5)

[[  5  10 -15  20  25]
 [-25  20  15  10  45]
 [ 20  40 -15  20   0]
 [  5  10  15 -20  45]]


In [38]:
print(array10+2)

[[ 3  4 -1  6  7]
 [-3  6  5  4 11]
 [ 6 10 -1  6  2]
 [ 3  4  5 -2 11]]


In [39]:
# Matriz transposta -> transpoe a matriz em colunas) O que era coluna virou linha
array10.T

array([[ 1, -5,  4,  1],
       [ 2,  4,  8,  2],
       [-3,  3, -3,  3],
       [ 4,  2,  4, -4],
       [ 5,  9,  0,  9]])

In [40]:
print(array10.max())

9


In [41]:
print(array10.max(axis=0)) # axis 0 -> colunas

[4 8 3 4 9]


In [42]:
array10

array([[ 1,  2, -3,  4,  5],
       [-5,  4,  3,  2,  9],
       [ 4,  8, -3,  4,  0],
       [ 1,  2,  3, -4,  9]])

In [43]:
print(array10.max(axis=1)) # axis 1 -> linhas

[5 9 8 9]


In [44]:
print(array10.min(axis=1)) # axis 1 -> linhas

[-3 -5 -3 -4]


In [45]:
print(array10.max(axis=0)) # axis 0 -> colunas

[4 8 3 4 9]


In [46]:
print(array10.sum())

46


In [47]:
print(array10.cumsum(axis=1)) # acomula linha a linha

[[ 1  3  0  4  9]
 [-5 -1  2  4 13]
 [ 4 12  9 13 13]
 [ 1  3  6  2 11]]


In [48]:
print(array10.cumsum(axis=0))

[[ 1  2 -3  4  5]
 [-4  6  0  6 14]
 [ 0 14 -3 10 14]
 [ 1 16  0  6 23]]


In [49]:
print(array10.cumprod(axis=0))

[[   1    2   -3    4    5]
 [  -5    8   -9    8   45]
 [ -20   64   27   32    0]
 [ -20  128   81 -128    0]]


In [50]:
array11 = np.array([[1,2], [5,4]])

In [51]:
array12 = np.array([[4,5], [2,1]])

In [52]:
print(array11+array12)

[[5 7]
 [7 5]]


In [53]:
print(array11*array12)

[[ 4 10]
 [10  4]]


In [54]:
print(array11.dot(array12))

[[ 8  7]
 [28 29]]


In [55]:
array_pi = np.array([0,np.pi/2, np.pi])

In [56]:
print(array_pi)

[0.         1.57079633 3.14159265]


In [57]:
print(np.cos(array_pi))

[ 1.000000e+00  6.123234e-17 -1.000000e+00]


In [58]:
np.mean(array_pi)

1.5707963267948966

In [59]:
import time

In [60]:
size = 1000000

In [61]:
list1 = range(size)

In [62]:
list2 = range(size)

In [63]:
array14 = np.arange(size)
array15 = np.arange(size)

In [64]:
initialTime = time.time()

lista_resultante = [(a*b) for a,b in zip(list1, list2)]
print(time.time() - initialTime)

0.14320755004882812


In [65]:
initialTime = time.time()

resultanteArray= array14 * array15
print(time.time() - initialTime)

0.02204751968383789


In [66]:
# Array e mais rapido e eficiente doq listas (68x mais rapido)
0.14063429832458496/0.002039194107055664

68.96562609610663

# Comparacao de elemento a elemento

In [67]:
a = np.array([100,104,201])
b = np.array([200,94,231])

In [68]:
print(np.greater(a,b))

[False  True False]


In [69]:
print(np.less(a,b))

[ True False  True]


In [70]:
print(np.greater_equal(a,b))

[False  True False]


In [71]:
print(np.less_equal(a,b))

[ True False  True]


In [72]:
print(np.array_equal(a,b))

False


In [73]:
np.unique(array10)

array([-5, -4, -3,  0,  1,  2,  3,  4,  5,  8,  9])

In [74]:
# unindo tabelas
np.union1d(a,b)

array([ 94, 100, 104, 200, 201, 231])

In [75]:
array_empty = np.empty((3,3))

In [76]:
print(array_empty)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [77]:
array_eye = np.eye(5)

In [78]:
# Matriz identidade
print(array_eye)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [79]:
array_ident = np.identity(5)

In [80]:
print(array_ident)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


# Algebra Linear

In [81]:
arrayAL = np.array([[6,5,3], [4, -3, 5], [2, 6, 9]])

In [82]:
print(arrayAL)

[[ 6  5  3]
 [ 4 -3  5]
 [ 2  6  9]]


In [83]:
np.linalg.matrix_rank(arrayAL)

3

In [84]:
np.linalg.det(arrayAL)

-382.00000000000006

In [85]:
np.linalg.inv(arrayAL)

array([[ 0.14921466,  0.07068063, -0.08900524],
       [ 0.06806283, -0.12565445,  0.04712042],
       [-0.07853403,  0.06806283,  0.09947644]])

In [86]:
np.trace(arrayAL)

12

In [87]:
array_j=np.array([[1,-2j],[2j,5]])

In [88]:
array_c, array_d = np.linalg.eigh(array_j)

In [89]:
print(array_c)

[0.17157288 5.82842712]


In [90]:
print(array_d)

[[-0.92387953+0.j         -0.38268343+0.j        ]
 [ 0.        +0.38268343j  0.        -0.92387953j]]


In [91]:
array_a=np.diag((1,2,3))

In [92]:
print(array_a)

[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [93]:
array_c, array_d = np.linalg.eig(array_a)

In [94]:
print(array_c)

[1. 2. 3.]


In [95]:
print(array_d)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [97]:
# Produto de 2 vetores -> numeros complexos
np.vdot()

TypeError: vdot() missing 2 required positional arguments: 'a' and 'b'

In [98]:
a = np.array([[1,2],[3,4]])

In [ ]:
b=np.array([6,14])

In [ ]:
np.linalg.solve(a,b)

In [ ]:
import matplotlib.pyplot as plt

In [ ]:
x = np.arange(0,9)

In [ ]:
A = np.array([x,np.ones(9)])
print(A)
print(A.T)

In [ ]:
y=[18, 20, 21.5, 22.5, 23, 23, 24.5, 25.6, 26]

In [ ]:
w = np.linalg.lstsq(A.T,y)[0]

In [ ]:
linha=w[0]*x+w[1]
plt.plot(x,linha, 'r-') #plt.plot(x,linha, `r-`)
plt.plot(x,y, 'o') # plt.plot(x,y, `o`)
plt.show()

# Pandas

In [ ]:
import pandas as pd

In [ ]:
# criando uma serie de pandas - Tipo um array de numpy
serie = pd.Series()

In [ ]:
print(serie)

In [ ]:
dado = np.array(["s", "e", "r", "i", "e"])
serie=pd.Series(dado)

In [ ]:
print(serie)

In [ ]:
df = pd.DataFrame()
print(df)

In [ ]:
lista = ['Conjunto', 'de', 'Valores', 'Armazenado'] 

In [ ]:
df = pd.DataFrame(lista)
print(df) #dataframe ja indexado 

In [ ]:
data = {'Nome': ['Gabriela', 'Isabela', 'Pedro', 'Thiago', 'Samuel'],
        'Idade': [19, 18, 21, 20, 20],
       'Cidade': ['Sao Paulo', 'Sao Paulo', 'Praia Grande', 'Praia Grande', 'Sao Paulo']}

In [ ]:
df=pd.DataFrame(data)

In [ ]:
print(df)

In [ ]:
print(df[['Nome', 'Cidade']])

In [ ]:
df.iloc[0]